tofu-tf/tofu

README.md

You wouldn't believe that. But I think I mastered that readme to be perfect.

Fix typos that have been introduced by fixing typos.

---

README.md
build.sbt
optics/macro/src/main/scala/tofu/optics/macros/GenContains.scala
optics/macro/src/main/scala/tofu/optics/macros/GenEquivalent.scala
optics/macro/src/main/scala/tofu/optics/macros/GenSubset.scala
optics/macro/src/main/scala/tofu/optics/macros/Optics.scala
optics/macro/src/main/scala/tofu/optics/macros/internal/Macro.scala
optics/macro/src/test/scala/tofu/optics/macros/GenContainsSpec.scala
optics/macro/src/test/scala/tofu/optics/macros/GenEquivalentSpec.scala
optics/macro/src/test/scala/tofu/optics/macros/GenSubsetSpec.scala
optics/macro/src/test/scala/tofu/optics/macros/TestDomain.scala
project/Dependencies.scala

This module is actually a `monocle-macro` port

optics-macro module

---

build.sbt
logging/structured/src/main/scala/tofu/logging/Logging.scala
logging/structured/src/main/scala/tofu/logging/TethysBuilder.scala
optics/core/src/main/scala/tofu/optics/Same.scala
parallel/src/main/scala/tofu/parallel/Splitting.scala

Having #8 merged, this PR will make the whole build clean, suppressing all warnings. Done as a separate PR, because may be considered debatable.

Add silencer

---

concurrent/src/test/scala/tofu/concurrent/ReadWriteTests.scala

increase sleeping time a little bit

---

concurrent/src/main/scala/tofu/concurrent/Daemon.scala
concurrent/src/main/scala/tofu/concurrent/MakeDeferred.scala
concurrent/src/main/scala/tofu/concurrent/package.scala
concurrent/src/main/scala/tofu/concurrent/syntax/daemon.scala
project/Dependencies.scala

That would make Daemons something like ZIO fibers, allowing polling unfinished processes for final results

Extended Daemons

---

build.sbt
logging/layout/src/main/scala/tofu/logging/ELKLayout.scala
logging/layout/src/main/scala/tofu/logging/logback/IEventLoggable.scala
logging/structured/src/main/scala/tofu/logging/Logging.scala
logging/structured/src/main/scala/tofu/logging/impl/LoggingImpl.scala

make LoggingImpl package private

refactor elk logging

---

core/src/main/scala/tofu/Guarantee.scala
core/src/main/scala/tofu/package.scala
core/src/main/scala/tofu/syntax/bracket.scala

new Finally typeclass

---

logging/derivation/src/main/scala/tofu/logging/derivation/loggable.scala
logging/layout/src/main/scala/tofu/logging/ELKLayout.scala
logging/layout/src/main/scala/tofu/logging/logback/IEventLoggable.scala
logging/structured/src/main/scala/tofu/logging/Loggable.scala

Also recalculating loggable instance

Grouping logging values

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

The Github Action will collect merged PR's titles as release notes to a draft release. The draft release will be updated on each merge to master.

Added Release Drafter app to collect release notes

---

logging/derivation/src/main/scala/tofu/logging/derivation/annotations.scala
logging/derivation/src/main/scala/tofu/logging/derivation/loggable.scala
logging/derivation/src/main/scala/tofu/logging/derivation/masking.scala
logging/derivation/src/main/scala/tofu/logging/derivation/package.scala
logging/derivation/src/main/scala/tofu/logging/derivation/show.scala

1. `MaskMode.Erased` acts like `erased == true`
2. `MaskMode.Full` acts like `erased == false`
3. `MaskMode.ForLength(offset, maxLength)`
starts masking from `offset` until `maxLength` count of symbols were masked. `maxLength == -1` acts like total string length,

Add mode to @masked annotation

---

optics/core/src/main/scala/tofu/optics/functions.scala

add option/either functions

---

concurrent/src/main/scala/tofu/concurrent/syntax/traverse.scala

Deprecated limitedTraverse.

---

core/src/main/scala/tofu/syntax/context.scala

Refine tofu.syntax.context

---

build.sbt

Tidy up project description

---

concurrent/src/main/scala/tofu/concurrent/ReadWrite.scala
core/src/main/scala/tofu/common/Console.scala
core/src/main/scala/tofu/syntax/console.scala
docs/memo.md
website/i18n/en.json

Add console syntax module.console-syntax

---

core/src/main/scala/tofu/syntax/foption.scala
core/src/test/scala/tofu/syntax/FOptionSuite.scala

Add convenient syntax for working with F[Option[A]]

---

core/src/main/scala/tofu/syntax/foption.scala
core/src/test/scala/tofu/syntax/FOptionSuite.scala

Just wrote few another syntax methods.

Yet another F[Option[A]] syntax

---

concurrent/src/main/scala/tofu/concurrent/impl/FocusedRef.scala
core/src/main/scala/tofu/lift/Unlift.scala
core/src/main/scala/tofu/package.scala
core/src/test/scala/tofu/lift/UnliftSuite.scala

Populate Lift companion with instances

Properly populate Lift/Unlift companions with instances

---

optics/core/src/main/scala/tofu/optics/functions.scala
zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
zio/core/src/main/scala/tofu/zioInstances/implicits.scala
zio/core/src/main/scala/tofu/zioInstances/package.scala
zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuit.scala

1. Small fixes
2. Added implicits for `Unlift`

Fix zio interop instances and implicits

---

fs2/src/main/scala/tofu/fs2Instances/fs2Instances.scala

Fix FS2 instances after merge of PR #210

---

logging/structured/src/main/scala/tofu/logging/impl/EmbedLogging.scala

Fix EmbedLogging parameters passing

---

env/src/main/scala/tofu/env/EnvInstances.scala

This is to make UnliftIO instance more derivable

Fix derivation of UnliftIO[Env[E, *]]

---

README.md
build.sbt
logging/interop/shapeless/src/main/scala/tofu/logging/shapeless/implicits.scala
logging/interop/shapeless/src/test/scala/tofu/logging/shapeless/TofuShapelessIntegrationSpec.scala
project/Dependencies.scala

Logging-Shapeless integration

---

README.md
build.sbt
logging/interop/refined/src/main/scala/tofu/logging/refined/refined.scala
logging/interop/refined/src/test/scala/tofu/logging/refined/TofuRefinedIntegrationSpec.scala
project/Dependencies.scala

Logging-Refined integration

---

core/src/main/scala/tofu/Fire.scala
core/src/main/scala/tofu/internal/NonTofu.scala
core/src/test/scala/tofu/IOSummonChecks.scala
env/src/main/scala/tofu/env/Env.scala
env/src/main/scala/tofu/env/EnvFunctorstance.scala
env/src/test/scala/tofu/env/EnvSummonChecks.scala

Fix Derivation of Fire[Env[R, *]]

---

concurrent/src/main/scala/tofu/concurrent/Atom.scala
core/src/main/scala/tofu/Timeout.scala
core/src/test/scala/tofu/TimeoutChecks.scala
env/src/main/scala/tofu/env/Env.scala
env/src/main/scala/tofu/env/EnvInstances.scala
zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala

Timeout avoid composing with fallback in the Timeout implementation

---

build.sbt
core/src/main/scala/tofu/common/time.scala
core/src/main/scala/tofu/package.scala
core/src/main/scala/tofu/syntax/time.scala
zio/core/src/main/scala/tofu/zioOptics.scala

Support simple time and date operations

---

build.sbt

Add logging interop modules to build.sbt properly

---

logging/structured/src/main/scala/tofu/logging/Loggable.scala

java.sql time-related datatypes loggable instances

---

core/src/main/scala/tofu/Errors.scala
core/src/main/scala/tofu/syntax/error.scala
core/src/main/scala/tofu/syntax/feither.scala
core/src/test/scala/tofu/ErrorsSuite.scala

Add reRaise and adaptError methods

---

docs/timeout.md
website/sidebars.json

add timeout docs

---

project/Dependencies.scala

There are incompatible changes related to `Duration`

Update zio/zio-interop-cats to stable versions  at a time

---

core/src/main/scala/tofu/Errors.scala
core/src/main/scala/tofu/errorInstances/package.scala
core/src/main/scala/tofu/internal/NonTofu.scala
zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuite.scala

Errors hierarchy fix. Remove subtype instance adapting from cats

---

.gitignore
core/src/main/scala/tofu/Errors.scala
core/src/main/scala/tofu/syntax/error.scala

Special thanks to @neko-kai for teaching me basic scala
fixes #369

Refactor of Error instance hierarchy

---

concurrent/src/main/scala/tofu/concurrent/ContextT.scala
concurrent/src/main/scala/tofu/concurrent/impl/contextt.scala

Provide contextShift instance for ContextT

---

concurrent/src/main/scala/tofu/concurrent/Daemon.scala
concurrent/src/main/scala/tofu/concurrent/syntax/deferred.scala
concurrent/src/test/scala/tofu/concurrent/DeferredSyntaxSuite.scala
higherKindCore/src/main/scala/tofu/higherKind/Function2K.scala

Fix daemon cancelation completion

---

core/src/main/scala/tofu/Errors.scala
core/src/main/scala/tofu/lift/Unlift.scala
core/src/test/scala/tofu/lift/UnliftSuite.scala
data/src/main/scala/tofu/data/calc/Continue.scala

Extra Unlift intstances

---

core/src/main/scala/tofu/Errors.scala
core/src/main/scala/tofu/syntax/error.scala
core/src/test/scala/tofu/RaiseSute.scala

Special search for `Raise` in syntax where only error type is known

---

core/src/main/scala/tofu/Scoped.scala
core/src/main/scala/tofu/package.scala
doobie/src/main/scala/tofu/doobie/log/EmbeddableLogHandler.scala

Add summon objects for Scoped aliases

---

derivation/src/test/scala/tofu/higherKind/derived/RepresentableKSuite.scala
higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala

[tofu-derivation] Narrow scope to unimplemented methods only

---

build.sbt
docs/logging.md
logging/interop/log4cats/src/main/scala/tofu/logging/log4cats/package.scala
project/Dependencies.scala

This implements a small integration module for transforming tofu Logging to log4cats Logger

Integration with log4cats

---

docs/mid.md
website/sidebars.json

translate Oleg's [note](https://gist.github.com/Odomontois/18503ae41f9b283227dbee727a627468)

Add Mid documentation

---

core/src/main/scala/tofu/Context.scala

~~It's WIP for now, but feel free to comment and improve it.~~
Note that examples do not compile and never will.

Scaladoc for Context.scala

---

core/src/main/scala/tofu/Errors.scala
core/src/test/scala/tofu/IOSummonChecks.scala
core/src/test/scala/tofu/RaiseSute.scala

Conflicting Errors instances

---

concurrent/src/main/scala/tofu/concurrent/Daemon.scala

Could be useful if you want to build remote actor.

Allow to implement custom Actors

---

.github/workflows/scala.yml

Update JDK in CI

---

doobie/src/main/scala/tofu/doobie/transactor/Txr.scala
doobie/src/main/scala/tofu/syntax/doobie/package.scala
doobie/src/main/scala/tofu/syntax/doobie/txr.scala
doobie/src/test/scala/tofu/doobie/TxrSuite.scala
doobie/src/test/scala/tofu/doobie/example/TofuDoobieExample.scala

- define Aux alias via bounds
- add Txr implicit summoners
- add txr syntax: trans/rawTrans
- improve example

Improve Txr usability

---

core/src/main/scala/tofu/Errors.scala
core/src/test/scala/tofu/ErrorsCompanion.scala

Adds errors companion with type aliases (same as for Context)

Errors companion with type aliases

---

higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala

Reworked a bit after migration to cats-tagless 0.13.0

Cleanup macros for HK derivation

---

build.sbt

Release 0.10.2

---

modules/config/src/main/scala/tofu/config/ConfigItem.scala
modules/config/src/main/scala/tofu/config/Configurable.scala
modules/config/src/test/resources/suite.conf
modules/config/src/test/scala/tofu/config/ConfigSuite.scala

Which is a common case when config expanded \ modified by the environment

[Config] Allow simple types to be parsed from strings

---

modules/logging/derivation/src/main/scala/tofu/logging/derivation/loggable.scala
modules/logging/derivation/src/test/scala/tofu/logging/derivation/DerivedLoggableSuite.scala
modules/logging/structured/src/main/scala/tofu/logging/Loggable.scala
modules/logging/structured/src/main/scala/tofu/logging/LoggableInstances.scala

Apply masking to logged fields

---

modules/zio/core/src/main/scala/tofu/zioInstances/implicits.scala
modules/zio/core/src/test/scala/tofu/zioInstances/ZioInstancesSuite.scala

lower priority of zioTofuErrorsToInstance

---

README.md
docs/hascontext.md
docs/installation.md
docs/streams.md

Besides core atrifacts names fix docs title in mircosite.

Docs fixes

---

modules/logging/structured/src/main/scala/tofu/logging/Loggable.scala
modules/logging/structured/src/main/scala/tofu/logging/impl/PlusLoggable.scala
modules/logging/structured/src/main/scala/tofu/logging/impl/SingletonLoggable.scala
modules/logging/structured/src/test/scala/tofu/logging/NamedLoggableCompositionSuite.scala

fix PlusLoggable, add SingletonLoggable

---

docs/tofu.logging.home.md
modules/kernel/src/main/scala/tofu/Delay.scala
modules/logging/structured/src/main/scala/tofu/logging/Logs.scala

Also fixed a couple of typos in deprecation warnings.

Add ce2 & ce3 docs entries to logging docs

---

modules/core/src/test/scala/tofu/IOSummonChecks.scala
modules/core3/src/test/scala/tofu/IOSummonChecks.scala

Remove type holes for kind-projector where it's unnecessary 

---

modules/kernel/src/main/scala/tofu/internal/ContextBase.scala

fix summon unlift from effect lower implicits search

---

docs/tofu.logging.recipes.context.md

Signed-off-by: Aristov Ivan <apostrof1995@gmail.com>

fix logging docs

---

modules/fs2/src/test/scala/tofu/fs2Instances/Fs2InteropContextAmbiguity.scala
modules/kernel/src/main/scala/tofu/WithContext.scala

Fix context diverge

---

modules/optics/core/src/main/scala/tofu/optics/Property.scala
modules/optics/core/src/main/scala/tofu/optics/Update.scala

For consistency like updateF/putF

Add setF method

---

.github/workflows/ci.yml
build.sbt
modules/concurrent/src/main/scala/tofu/concurrent/ContextT.scala
modules/concurrent/src/test/scala/tofu/concurrent/ContextTRebaseSuite.scala
modules/higherKindCore/src/main/scala/tofu/higherKind/Embed.scala
modules/higherKindCore/src/main/scala/tofu/higherKind/MonoidalK.scala
modules/higherKindCore/src/main/scala/tofu/higherKind/PureK.scala
modules/higherKindCore/src/main/scala/tofu/higherKind/RepresentableK.scala
modules/higherKindCore/src/main/scala/tofu/internal/EffectCompHK.scala
modules/higherKindCore/src/main/scala/tofu/syntax/monoidalK.scala
modules/kernel/src/main/scala/tofu/common/Console.scala
modules/kernel/src/main/scala/tofu/generate/GenRandom.scala
modules/kernel/src/main/scala/tofu/generate/GenUUID.scala
modules/logging/structured/src/main/scala/tofu/logging/Loggable.scala
modules/logging/structured/src/main/scala/tofu/logging/LoggableInstances.scala
modules/logging/structured/src/main/scala/tofu/logging/Logging.scala
modules/memo/src/main/scala/tofu/memo/Memoize.scala
project/Dependencies.scala
project/plugins.sbt

Update scala 2.13

---

build.sbt
examples-zio2/src/main/scala/tofu/example/logging/LogKey.scala
examples-zio2/src/main/scala/tofu/example/logging/ZioLoggingNativeExample.scala
modules/zio2/logging/src/main/scala/tofu/logging/impl/TofuDefaultContextImpl.scala
modules/zio2/logging/src/main/scala/tofu/logging/impl/TofuDefaultWithZIOContextImpl.scala
modules/zio2/logging/src/main/scala/tofu/logging/zlogs/TofuDefaultContext.scala
modules/zio2/logging/src/main/scala/tofu/logging/zlogs/TofuZLogger.scala
modules/zio2/logging/src/main/scala/tofu/logging/zlogs/ZLogAnnotation.scala
modules/zio2/logging/src/test/scala/tofu/logging/zlogs/LogKey.scala
modules/zio2/logging/src/test/scala/tofu/logging/zlogs/TestStuff.scala
modules/zio2/logging/src/test/scala/tofu/logging/zlogs/TofuDefaultContextSpec.scala
modules/zio2/logging/src/test/scala/tofu/logging/zlogs/ZLogsTest.scala
project/Dependencies.scala

- implement TofuZLogger - a native ZLogger
- implement ZLogAnnotations - adds tofu context
- add TofuDefaultContext  - provides tofu context for tofu loggers
- write TofuDefaultContext test
- write ZIO native examples
This is the finishing version of the work, next PR will bring only docs, tests and maybe minor improvements

ZIO-2 logging (Part 2)

---

modules/kernel/src/main/scala/tofu/control/impl/ApplyDelegate.scala
project/Dependencies.scala

Upgrade cats

---

examples-ce3/src/main/scala/tofu/example/doobie/TofuDoobieExample.scala
project/Dependencies.scala

update fs2 (CE3)

---

build.sbt
docs/tofu.logging.home.md
docs/tofu.logging.recipes.zio2.md

Remove zio2 from docs dependencies

fix zio2 logging docs

---

modules/kernel/higherKind/src/main/scala-2/tofu/higherKind/Mid.scala
modules/kernel/higherKind/src/test/scala-2/tofu/higherKind/MidSuite.scala

#1112 
I did a quick reasoning and it seems to be a lawful instance

feat: +invariantK instance for Mid

---

build.sbt
modules/logging/interop/log4cats-legacy/src/main/scala-2/tofu/logging/log4cats/package.scala
project/Dependencies.scala

Old version will be named 
tofu-logging-log4cats-legacy

Support new version of log4cats.

---

docs/tofu.logging.recipes.zio2.md
examples/zio2/src/main/scala-2/tofu/example/logging/ZioLoggingNativeExample.scala
modules/interop/zio2/logging/src/main/scala-2/tofu/logging/zlogs/TofuZLogger.scala
modules/interop/zio2/logging/src/main/scala-2/tofu/logging/zlogs/ZLogAnnotation.scala
modules/interop/zio2/logging/src/test/scala-2/tofu/logging/zlogs/TofuDefaultContextSpec.scala

- added slf4j initialization call, because in some cases of program failure it may happen that the program exits before the log message is written.
- scoped log annotations added for convenience

zio-logging improvements

---

modules/core/ce2/src/test/scala/tofu/TimeoutChecks.scala
modules/core/ce2/src/test/scala/tofu/TimeoutSuite.scala
modules/core/ce3/src/test/scala/tofu/TimeoutChecks.scala
modules/core/ce3/src/test/scala/tofu/TimeoutSuite.scala
modules/kernel/src/main/scala/tofu/lift/Unlift.scala
modules/kernel/src/main/scala/tofu/time/Timeout.scala

Hi, I'm adding transformers support for timeout as suggested here https://github.com/tofu-tf/tofu/pull/1245 ;  I'm trying not to create PR more than 300 lines to make it easier to review, so I'll add transformers support for `Fire` later. Or if you think it's unnecessary, then I'll continue in the same PR (please let me know)

Add transformers support for `Timeout`

---

modules/kernel/src/main/scala-3/tofu/internal/Interop.scala
project/plugins.sbt

tpolecat plugin version was updated in this PR.
Also symbol exists check was fixed.

tpolecat plugin update

---

website/src/pages/index.js

Improve English on microsite

---

.github/workflows/ci.yml
build.sbt

add missing `dependsOn` to root tofu project

---

build.sbt

Fixes this issue - https://github.com/tofu-tf/tofu/actions/runs/13336887297/job/37254115426#step:6:1336

fix: log4catsLegacy3 

---

.github/workflows/ci.yml

Fix for this failed job - https://github.com/tofu-tf/tofu/actions/runs/13367396875/job/37328111449

fix: avoid double docs uplooad to gh-pages
