tofu-tf/tofu

- project/Dependencies.scala
The build depends on an unpublished version of `derevo`. Change version to the latest one available on Central.
> Fix missing dependency

- core/src/main/scala/tofu/Context.scala
- core/src/main/scala/tofu/package.scala
- core/src/main/scala/tofu/syntax/context.scala
- core/src/test/scala/tofu/ContextSuite.scala
This PR is to address 2 issues.
1. `RunContext` instances (namely `ReaderT` instance) don't expose their lower effect in the signature, so that it remains a path-dependent member after `runContext` is invoked.
2. There is a [known issue](https://github.com/scala/bug/issues/10582) in scalac with type aliases and implicit resolution. `Context` uses a mix of `Aux`/`Has***` aliases. It causes errors, if a user requires a constraint via one alias while a syntax extension requires the other. (See the `testRunContextSyntax` test, which would fail without this fix). Using only one set of aliases would be a reasonable solution. Since these aliases are used for parameterization of traits being mixed in companion objects, Aux pattern doesn't work out (causing _illegal cyclic reference involving …
> Expose lower effect in RunContext instances

- logging/structured/src/main/scala/tofu/logging/Loggable.scala
- logging/structured/src/main/scala/tofu/logging/Logging.scala
- logging/structured/src/main/scala/tofu/logging/impl/ContextLoggingImpl.scala
- logging/structured/src/main/scala/tofu/logging/impl/ContextSyncLoggingImpl.scala
- logging/structured/src/main/scala/tofu/logging/impl/EmbedLogging.scala
- logging/structured/src/main/scala/tofu/logging/impl/LoggingImpl.scala
- logging/structured/src/main/scala/tofu/logging/impl/SyncLogging.scala
- logging/structured/src/main/scala/tofu/syntax/loggable.scala
As of SLF4J version 1.6.0, it is possible to log an exception along with a parameterized message. This PR adds some interpolators to use that feature.
> Add string interpolators for error logging

- logging/structured/src/main/scala/tofu/logging/impl/ContramapLoggable.scala
- logging/structured/src/main/scala/tofu/logging/impl/HiddenLoggable.scala
- logging/structured/src/test/scala/tofu/logging/LoggableSuite.scala
Bug: Hiding LoggedValue depends on order of Loggable modifiers
For example
```
Loggable.intLoggable.named("responseTime").hide.contramap(_.value)
```
doesn't hide value, but
```
Loggable.intLoggable.hide.named("responseTime").contramap(_.value)
```
does.
This make it independent of modifiers order by removing `loggedValue` overriding in proxies
> Fix hiding order dependency in Loggable

- core/src/main/scala/tofu/syntax/error.scala
> Require at least `ContravariantRaise` instance for `raise` syntax.

- env/src/main/scala/tofu/env/Env.scala
Add simple .timed combinator, delegating to `Task.timed`
> Add .timed combinator

- config/src/main/scala/tofu/config/ConfigMonad.scala
- core/src/main/scala/tofu/Errors.scala
- core/src/main/scala/tofu/errorInstances/package.scala
- optics/core/src/main/scala/tofu/optics/functions.scala
- zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
- zio/core/src/main/scala/tofu/zioInstances/package.scala
> `RestoreTo[F[_], G[_]]` extends `Lift[G[_], F[_]]`.

- docs/hascontext.md
A small `HasContext` usage example. This code compiles and the main point that it shows its usage without `tofu.Env`. Can be pretty important for the entire `HasContex` understanding. 
It does not cover optics API.
> Add HasContext docs

- core/src/main/scala/tofu/syntax/traverse.scala
Im not sure how one can achieve following signature from issue: `traverseKey(f: A => F[B]): F[(A, B)]` since Traverse embeds `T[_]` inside `F[_]`, so I did it for `traverseKey(f: A => F[B]): F[T[(A, B)]]`
Resolves #127
> Add traverseKey/traverseKeyFilter operations

- docs/hascontext.md
Fix my typo in docs and adds a more extended Context with Extractors usage example.
> Fix the spelling and extend documentation

- core/src/main/scala/tofu/Context.scala
- docs/hascontext.md
As an alternative to the [ApplicativeAsk.const](https://github.com/typelevel/cats-mtl/blob/9268fcb1469e53ba601bc765cf7d4f78e0b9e45a/core/src/main/scala/cats/mtl/ApplicativeAsk.scala#L36) from cats-mtl, it can be convenient to have a function that lifts values to the Context.
This idea and the code were brought by @optician
> Add Context.const function that lifts value into a Context

- concurrent/src/main/scala/tofu/concurrent/impl/FocusedRef.scala
- logging/layout/src/main/scala/tofu/logging/ELKLayout.scala
`ELKLayout` extends `PatternLayout` but doesn't support patterns by design. This leads to an initialization error:
```ERROR in tofu.logging.ELKLayout("null") - Empty or null pattern.```
Change parent class to `LayoutBase`.
> Fix logback error in ELKLayout initialization

- concurrent/src/main/scala/tofu/concurrent/impl/FocusedRef.scala
- logging/structured/src/main/scala/tofu/logging/Logging.scala
- logging/structured/src/main/scala/tofu/logging/Logs.scala
1. Removed the `Embed[Logging]` instance overlapped by the `RepresentableK[Logging]` instance and thus unsummonable.
2. Added `MonoidalK` instances for `Logs` for the second type param.
> Add higher kinded typeclass instances for Logs

- higherKindCore/src/main/scala/tofu/higherKind/Mid.scala
- higherKindCore/src/main/scala/tofu/higherKind/Post.scala
- higherKindCore/src/main/scala/tofu/higherKind/Pre.scala
- higherKindCore/src/test/scala/tofu/higherKind/MidSuite.scala
`Semigroup[U[Mid[F, *]]]` was unsummonable (having `ApplyK[U]`) due to a hidden instance.
> Fix implicit hiding for Mid

- logging/structured/src/main/scala/tofu/logging/LoggableContext.scala
- logging/structured/src/test/scala/tofu/logging/LoggableContextSuite.scala
Current implementation of `LoggableContext` companion with its summoner method doesn't allow resolving ambiguity if there are several `Context[F]` instances in the scope (except for passing the needed instance explicitly).
The new implementation works in the same way as the previous one if there's no ambiguity, but also allows choosing the right context by specifying a type param:
```scala
LoggableContext.of[F].instance
LoggableContext.of[F].instance[C]
```
> Allow summoning LoggableContext unambiguously

- build.sbt
- logging/structured/src/main/scala/tofu/logging/Loggable.scala
- logging/structured/src/main/scala/tofu/logging/impl/EmptyLoggable.scala
- project/Dependencies.scala
- zio/logging/src/main/scala/tofu/logging/zlogs/ZLogs.scala
- zio/logging/src/main/scala/tofu/logging/zlogs/ZioHasBuilder.scala
- zio/logging/src/main/scala/tofu/logging/zlogs/package.scala
- zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
Basically it gives some interop with zio.Has.
One can now easely define set of components, that should be logged during each operation.
Also define an embedded instance `Loggable[URIO[R, *]]` where `R <: Has[Loggable[URIO[R1, *]]`
> ZIO logging read context from Has, provide embedded Logger

- config/src/main/scala/tofu/config/ConfigMonad.scala
Sometimes, if config is invalid, tofu.config fails with exception:
```
tofu.config.ConfigTContext$Fail$: null
at tofu.config.ConfigTContext$Fail$.<clinit>(ConfigMonad.scala:113)
at tofu.config.ConfigTContext$ConfigTConfigMonad$$anon$4.$anonfun$raise$1(ConfigMonad.scala:104)
...
```
Probably, it happens, because `case object Fail` in `object ConfigTContext` is used before it is declared. This PR fixes this problem
> Move ConfigTContext.Fail to top of object for initialization issues

- concurrent/src/main/scala/tofu/concurrent/Daemon.scala
- concurrent/src/test/scala/tofu/concurrent/DaemonTests.scala
This simple code can fail sometimes with "java.lang.IllegalStateException: Attempting to complete a Deferred that has already been completed" when using cats-effect or monix:
```scala
IO.pure(()).daemonize.flatMap(_.cancel)
```
This happens due to `bracket` implementation in cats-effect and monix which could execute `use` and `release` blocks concurrently.
> Fix Daemon cancellation

- zio/core/src/main/scala/tofu/zioInstances/ZioTofuConcurrentInstance.scala
- zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
Since ZIO 1.0.0-RC18 fibers are garbage collected if their parent fiber terminates. This breaks all "fire and forget" methods and introduces inconsistency with cats-effect and monix backed implementations. Replacing all `fork` calls with `forkDaemon` should return previous behavior.
> Use forkDaemon instead of fork in zio-interop

- core/src/main/scala/tofu/Timeout.scala
This method is not referenced anywhere and it seems like `implicit` keyword is missing.
Current workaround is to write `implicit val timeoutInstance: Timeout[F] = Timeout.concurrent` and this doesn't look right
> Make Timeout instance for Concurrent types implicit

- higherKindCore/src/main/scala/tofu/syntax/monadic.scala
Code in `unless_` is the same as in the `when_` method, looks like a copy-paste bug
> replace branches in unless_ method

- core/src/main/scala/tofu/syntax/unlift.scala
- core/src/test/scala/tofu/syntax/UnliftSuite.scala
Add some extra methods to `Unlift` as extensions rather than trait members.
This addresses the well-known problem when you need a (Concurrent)Effect instance for a contextual effect, e.g. for integration with impure APIs or poorly designed libs, but you obviously cannot. `Unlift` solves this problem.
Usage:
```scala
Unlift[F, G].concurrentEffectWith { implicit CE => 
// pretend that you have ConcurrentEffect for G if you have the same for F
// while staying within the contextual effect G
needsConcurrentEffect[G]
}
```
The naming and signatures are taken from `zio.interop.catz`.
> Add Unlift extensions for summoning (Concurrent)Effect

- docs/internal/kind-enumeration.md
- docs/internal/variance-enumeration.md
This is an internal description of enumeration of kinds to shorten names for exotic things
> Kind enumeration description

- derivation/src/test/scala/tofu/higherKind/derived/RepresentableKVarArgSuite.scala
- higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
with current version this code fails to compile https://scastie.scala-lang.org/iN8saUZZRAC0Vl5x1Ssr4w
> fix RepresentableK macro for traits with vararg parameters in methods

- fs2/src/main/scala/tofu/fs2Syntax/pre.scala
Usage:
```scala
import cats.Applicative
import derevo.derive
import fs2.Stream
import tofu.fs2Syntax.pre._
import tofu.higherKind.Pre
import tofu.higherKind.derived.representableK
import tofu.syntax.monadic._
@derive(representableK)
trait StreamingAlg[S[_]] {
def foo(a: String): S[String]
}
object StreamingAlg {
def make[F[_] : Applicative]: StreamingAlg[Stream[F, *]] =
new AuthzPre[F].attachStream(new Impl[F])
final class Impl[F[_]] extends StreamingAlg[Stream[F, *]] {
def foo(a: String): Stream[F, String] = Stream.iterate(a)(x => x + x)
}
final class AuthzPre[F[_]: Applicative] extends StreamingAlg[Pre[F, *]] {
def foo(a: String): Pre[F, String] = Pre.apply(unit[F]) // may check privs and rise err
}
}
```
> Add Pre syntax for attaching fs2.Stream algebras

- core/src/main/scala/tofu/lift/Unlift.scala
- core/src/test/scala/tofu/lift/UnliftSuite.scala
The latter is needed in case when someone uses ReaderT[Task, R, *] instead of Env.
> Add Lift instances via IsoK, UnliftIO instance for ReaderT

- logging/layout/src/main/scala/tofu/logging/logback/IEventLoggable.scala
For now, ELKLayout only prints the stack trace of the passed exception, but its cause and suppressed exceptions are omitted. I think it would be more convenient to have a complete stack trace in the log.
> Print full stacktrace in ELKLayout

- zio/core/src/main/scala/tofu/zioInstances/ZioTofuConcurrentInstance.scala
- zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
This code will never finish with the current implementation:
```scala
ZManaged
.make(sleep(Duration.Infinity).daemonize)(_.cancel)
.use(_ => ZIO.succeed(ExitCode.success))
```
Resource acquiring in cats-effect and zio is uncancelable, and zio fibers inherit this property from their parent fiber. Adding `interruptible` should fix this issue, as is done in zio-interop-cats.
> Make started fibers interruptible in zio-interop

- build.sbt
- concurrent/src/main/scala/tofu/concurrent/Atom.scala
- concurrent/src/main/scala/tofu/concurrent/ContextT.scala
- concurrent/src/main/scala/tofu/concurrent/impl/contextt.scala
- core/src/main/scala/tofu/Errors.scala
- core/src/main/scala/tofu/control/impl/SelectiveInstances.scala
- core/src/main/scala/tofu/lift/Rebase.scala
- core/src/main/scala/tofu/syntax/selective.scala
- core/src/test/scala/tofu/syntax/RetrySuite.scala
- data/src/main/scala/tofu/data/calc/CalcMOps.scala
- data/src/main/scala/tofu/data/calc/CalcRunner.scala
- data/src/main/scala/tofu/data/data.scala
- higherKindCore/src/main/scala-2.12/tofu/compat/package.scala
- higherKindCore/src/main/scala-2.13/tofu/compat/package.scala
- higherKindCore/src/main/scala/tofu/syntax/monadic.scala
- src/test/scala/tofu/concurrent/ContextTRebaseSuite.scala
Here we introduce a new typeclass `Rebase` which is something in between of `InvariantK` and `FunctorK`
It main goal however - transforming higher kinded case classes serving as contexts, not traits.
Right now it forces user to construct instances manually, but we hope we can deliver automatic derivation later.
> Additional instances for ContextT and others

- docs/logging.md
I see no logging on my classpath with `libraryDependencies += "ru.tinkoff" %% "tofu" % "0.7.9"`
> Fix docs on logging installation

- .gitignore
- zio/core/src/main/scala/tofu/zioInstances/ZioTofuInstance.scala
> Fix zio executor retrieving for blocking

- streams/src/main/scala/tofu/syntax/streams/broadcast.scala
- streams/src/main/scala/tofu/syntax/streams/chunks.scala
- streams/src/main/scala/tofu/syntax/streams/combineK.scala
- streams/src/main/scala/tofu/syntax/streams/compile.scala
- streams/src/main/scala/tofu/syntax/streams/emits.scala
- streams/src/main/scala/tofu/syntax/streams/evals.scala
- streams/src/main/scala/tofu/syntax/streams/filter.scala
- streams/src/main/scala/tofu/syntax/streams/merge.scala
- streams/src/main/scala/tofu/syntax/streams/pace.scala
- streams/src/main/scala/tofu/syntax/streams/package.scala
- streams/src/main/scala/tofu/syntax/streams/parFlatten.scala
- streams/src/main/scala/tofu/syntax/streams/region.scala
- streams/src/main/scala/tofu/syntax/streams/temporal.scala
Streams syntax refactored in order to support imports like `import tofu.syntax.streams.all._` along with `import tofu.syntax.streams.<concrete_syntax>._`
> Streams syntax refactoring

- build.sbt
- logging/scribe/src/main/scala/org/slf4j/impl/StaticLoggerBinder.scala
- logging/scribe/src/main/scala/org/slf4j/impl/StaticMDCBinder.scala
- logging/scribe/src/main/scala/org/slf4j/impl/StaticMarkerBinder.scala
- logging/scribe/src/main/scala/tofu/logging/ELKFormatter.scala
- logging/scribe/src/main/scala/tofu/logging/scribe/RecordLoggable.scala
- logging/scribe/src/main/scala/tofu/logging/scribe/internal/MarkedOutput.scala
- logging/scribe/src/main/scala/tofu/logging/scribe/internal/ScribeLoggerAdapter.scala
- project/Dependencies.scala
Tofu Logging integration for [Scribe](https://github.com/outr/scribe)
Basically just a copypasta from tofu logback layout and scribe-slf4j with minor changes, bringing Marker context and Args Array support. Made for fun.
Example of logback.xml rewrite into Scribe dsl:
```xml
<configuration>
<appender name="rolling" class="ch.qos.logback.core.rolling.RollingFileAppender">
<file>logs/data.log</file>
<rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
<fileNamePattern>logs/data.%i.log</fileNamePattern>
<minIndex>0</minIndex>
<maxIndex>8</maxIndex>
</rollingPolicy>
<triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
<maxFileSize>50MB</maxFileSize>
</triggeringPolicy>
<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder"> …
```
> [WIP] Logging Layout and Marker context integration with Scribe

- streams/src/main/scala/tofu/syntax/streams/evals.scala
- streams/src/test/scala/tofu/streams/SyntaxTypeInferenceSuite.scala
Fixes error cases like this https://scastie.scala-lang.org/AekOpUbrRtaH4Fr5u9n4Fg
> `Lift` usage eliminated from `evals` syntax.

- core/src/main/scala/tofu/Errors.scala
`Raise` with upcasting still doesn't cover all the use cases of `ContravariantRaise`.
> `ContravariantRaise` undeprecated.

- derivation/src/test/scala/tofu/higherKind/derived/RepresentableKSuite.scala
- higherKindCore/src/main/scala/tofu/higherKind/derived/HigherKindedMacros.scala
> Revert #424

- core/src/main/scala/tofu/Context.scala
Helper method allowing to access dependencies in context in slightly more convenient way when there are multiple of them:
```scala
import tofu.syntax.context._
def foo[F[_]: Monad: Foo.Has: Bar.Has]: F[X] =
(hasContext[F, Foo], hasContext[F, Bar]).mapN((f, b) => ???)
```
vs
```scala
def foo[F[_]: Monad: Foo.Has: Bar.Has]: F[X] =
(Foo.access, Bar.access).mapN((f, b) => ???)
```
> Context accessor method

- core/src/main/scala/tofu/syntax/error.scala
- core/src/main/scala/tofu/syntax/feither.scala
- core/src/main/scala/tofu/syntax/foption.scala
- core/src/main/scala/tofu/syntax/timeout.scala
- core/src/test/scala/tofu/syntax/FindRaiseSuite.scala
Resolve issue with Raise[E, F] find in feither,foption,timeout and raise syntax since some methods haven`t been changed after introduction of FindRaise fix #513. 
Code snippet with a problem https://scastie.scala-lang.org/Qar66QORSFKa9oLRmGJ3bQ.
> FindRaise in feither, foption, timeout syntax

- build.sbt
This is to fix warnings in sbt:
```
[info] loading project definition from /home/runner/work/tofu/tofu/project
/home/runner/work/tofu/tofu/build.sbt:288: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
scalacOptions in (ScalaUnidoc, unidoc) += "-Ymacro-expand:none",
^
/home/runner/work/tofu/tofu/build.sbt:289: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
unidocProjectFilter in (ScalaUnidoc, unidoc) := inProjects(allModuleRefs: _*) -- inProjects(opticsMacro),
^
/home/runner/work/tofu/tofu/build.sbt:290: warning: …
```
> Drop sbt-0.13.x syntax

- data/src/main/scala/tofu/data/calc/CalcM.scala
- data/src/main/scala/tofu/data/calc/CalcMOps.scala
When you need covariant StateT, you can do
```scala
type StateT[+F[+_], S, +x] = CalcT[F, Any, S, S, Nothing, x]
```
This pull request adds helpers `stateT` and `runTailRecSingle`:
```scala
def pop: StateT[IO, Vector[Int], Option[Int]] =
CalcM.stateT(v =>
IO(println("popping")).as((v.tail, v.headOption))
)
def code: StateT[IO, Vector[Int], Unit] = {
for {
x <- pop
_ <- CalcT.lift(IO(println(x)))
y <- pop
_ <- CalcT.lift(IO(println(y)))
} yield ()
}
val run: IO[(Vector[Int], Unit)] = code.runTailRecSingle((), Vector(1, 2, 4, 5))
```
> CalcM methods for StateT

- README.md
- RMS logo is currently very large in comparison, scaling down to 15% width. 
- link also is broken so updating.
> Update RMS logo width and link

- website/siteConfig.js
The link in the user showcases currently links to https://docs.tofu.tf/en/tinkoff.ru because it is only relative.
> Fix Tinkoff link

- concurrent/src/main/scala/tofu/concurrent/Daemon.scala
- core/src/main/scala/tofu/package.scala
- core/src/test/scala/tofu/GuaranteeSuite.scala
- kernel/src/main/scala/tofu/Guarantee.scala
- kernel/src/main/scala/tofu/internal/Interop.scala
- kernel/src/main/scala/tofu/kernel/types.scala
- kernelCE2Interop/src/main/scala/tofu/interop/CE2Kernel.scala
This one is tricky. 
We had to use whitebox macros to allow optional instance to derive type that may be unconstructable in the using code and shapeless Aux encoding for intermediate carrier .
> Guarantee kernelize

- build.sbt
- kernel/src/main/scala/tofu/Context.scala
- kernel/src/main/scala/tofu/Has.scala
- kernel/src/main/scala/tofu/WithContext.scala
- kernel/src/main/scala/tofu/WithLocal.scala
- kernel/src/main/scala/tofu/WithProvide.scala
- kernel/src/main/scala/tofu/WithRun.scala
- kernel/src/main/scala/tofu/internal/ContextBase.scala
- kernel/src/main/scala/tofu/kernel/types.scala
- kernel/src/main/scala/tofu/lift/Unlift.scala
This PR moves WithContext, WithLocal, WithProvide, and WithRun from `Context.scala`.
Also, it marks HasContext and others as deprecated.
I was trying to keep this PR as simple as possible so it's kinda small.
> Context typeclasses

- build.sbt
- modules/derivation/src/main/scala/tofu/higherKind/derived/ContextEmbed.scala
Apparently, those modules are not using anything from `core`.
> Use kernel dependency for derivation, zioCore and streams modules.

- modules/kernel/src/main/scala/tofu/data/calc/CalcMOps.scala
> Add CalcM.tailrecEither

- .scala-steward.conf
Until we move to ce3 completely
> Exclude http4s from .scala-steward.conf

- modules/zio/logging/src/main/scala/tofu/logging/zlogs/ZLogging.scala
- modules/zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
Some warnings introduced in #782, somehow missed
> Fix unused warnings in logging

- modules/higherKindCore/src/main/scala/tofu/instances/bind.scala
- modules/higherKindCore/src/test/scala/tofu/control/CatsInstancesFromBindSuite.scala
From user perspective, when I require Bind instance in my code,
I want to have implicit cats.Monad instance for later usages. Now to do so
I have to write something like implicit def monad[E] = bind.monad[E]
in the beginning of the method, since most of the library methods accept
typeclasses as implicit parameters.
Assuming that Bind is right-biased, it makes perfect sense to write such
implicit conversion and use it in source file imports section.
> Implicit conversion from Bind to cats.Monad

- docs/tofu.logging.recipes.zio.md
- modules/logging/layout/src/test/resources/logback-test.xml
- modules/logging/layout/src/test/scala/tofu/logging/LogbackSuite.scala
- modules/logging/structured/src/main/scala/tofu/logging/impl/UniversalLogging.scala
- modules/zio/logging/src/main/scala/tofu/logging/impl/ZUniversalContextLogging.scala
- modules/zio/logging/src/main/scala/tofu/logging/impl/ZUniversalLogging.scala
- modules/zio/logging/src/main/scala/tofu/logging/zlogs/ZLogging.scala
When <level>Cause method is called the exception is wrapped in `tofu.logging.LoggedThrowable`. The PR fixes this unwanted behavior. 
Also references to the zio website are updated.
> zio-logging:  add writeMarkerCause, fix zio doc references

- docs/tofu.logging.home.md
The existing link in the `logging.home` documentation to the examples is broken and leads to 404.
This PR fixes the link to the logging examples by replacing it with a relative link.
> Chore: tofu.logging.home.md the examples link fix

- modules/logging/structured/src/main/scala/tofu/logging/LoggedValue.scala
- modules/logging/structured/src/main/scala/tofu/logging/impl/ComposedLoggedValue.scala
ContextMarker allows to provide only single LoggedValue. 
Writing ZIO2 logger I faced that I need to collect context (several LoggedValues) from different places (zio-annotations, zio-spans, user-defined context) and put it into ContextMarker. This several logged values (potentially named or constructed from Map[String, A]) must be logged as if they provided in arguments of logging-method.
> ComposedLoggedValue: single LoggedValue as several LoggedValues on the top-level

- .github/workflows/ci.yml
- build.sbt
- modules/core/src/test/scala/tofu/ScopedSuite.scala
- modules/core/src/test/scala/tofu/syntax/FEitherSuite.scala
- modules/core3/src/test/scala/tofu/syntax/FEitherSuite.scala
- modules/higherKindCore/src/test/scala/tofu/control/CatsInstancesFromBindSuite.scala
- modules/kernel/src/main/scala/tofu/internal/NonTofu.scala
- modules/logging/structured/src/main/scala/tofu/logging/TethysBuilder.scala
- modules/logging/structured/src/main/scala/tofu/logging/impl/ContextLoggingImpl.scala
- modules/logging/structured/src/main/scala/tofu/logging/impl/ContextSyncLoggingImpl.scala
- modules/logging/structured/src/main/scala/tofu/logging/impl/SyncLogging.scala
- modules/logging/structured/src/main/scala/tofu/logging/impl/UniversalLogging.scala
- modules/logging/structured/src/main/scala/tofu/logging/location/Location.scala
- modules/zio/logging/src/test/scala/tofu/logging/zlogs/ZLogsSuite.scala
- project/Dependencies.scala
> Upgrade scala 2.13 and circe

- docs/tofu.logging.home.md
Interop instances have moved to another module, fix according docs 
Fixes #1128
> docs: cats-effect interop moved to tofu-core-* modules

- .github/workflows/ci.yml
- build.sbt
- modules/kernel/src/main/scala/tofu/common/Console.scala
- modules/util/env/src/main/scala-2/tofu/env/EnvFunctions.scala
- project/plugins.sbt
After migration to project matrix plugin unidoc became broken because source code for all subprojects for different scala version was used to docs compilation (Unidoc plugin feature/bug).
The solution is to generate docs for only main version of scala (now it is 2.13) and to filter out unused subprojects with `unidocProjectFilter` setting.
Now doc commands (`unidoc`, `docusaurusCreateSite`, `docusaurusPublishGhpages`) can be launched in style with or without version specification (on root project) like this:
`unidoc`
`++2.13 unidoc`
Closes #1213
> Fix running `unidoc` and Docusaurus site creation

- modules/core/ce2/src/test/scala/tofu/time/TimeSuite.scala
- modules/core/ce3/src/test/scala/tofu/time/TimeSuite.scala
- modules/kernel/src/main/scala/tofu/time/Clock.scala
- modules/kernel/src/main/scala/tofu/time/Sleep.scala
Hi, I suggest to add same functionality from cats for effects, so I opened a small pull request to demonstrate what I propose. If it's ok, then in the new PR I'll do it for all transformers and all effects.
Here is an example with a demonstration of the problem: In the first case, with cats everything is fine; in the second case, the ide says that everything is fine, but we get a compilation error.
```scala
import cats.effect.{Clock => CatsClock}
// Ok
def catsClock[F[_]: Monad: CatsClock]: F[FiniteDuration] = {
val clock = CatsClock[ReaderT[F, String, *]]
clock.realTime.run("str")
}
import tofu.time.{Clock => TofuClock}
// Error `could not find implicit value for parameter e: tofu.time.Clock[[â•¬â”‚$1$]cats.data.Kleisli[F,String,â•¬â”‚$1$]]`
def tofuClock[F[_]: Monad: TofuClock]: F[Long] …
```
> feature: Add clockForKleisli and sleepForKleisli

- modules/core/ce2/src/test/scala/tofu/syntax/FEitherSuite.scala
- modules/kernel/src/main/scala/tofu/syntax/feither.scala
Hi, here is a small suggestion to add a new syntax for feather, the main goal was to add `doubleFlatTap` because I have often felt need in it. In the process, I added `asIn` and `asF` because they were needed for `doubleFlatTap`
> Add doubleFlatTap,asIn,asF into EitherFOps

- modules/core/ce2/src/test/scala/tofu/StartSuite.scala
- modules/core/ce3/src/test/scala/tofu/IOSummonChecks.scala
- modules/core/ce3/src/test/scala/tofu/StartSuite.scala
- modules/kernel/src/main/scala-2/tofu/internal/instances/FibersInstance.scala
- modules/kernel/src/main/scala-2/tofu/internal/instances/RaceInstance.scala
- modules/kernel/src/main/scala-3/tofu/internal/instances/FibersInstance.scala
- modules/kernel/src/main/scala-3/tofu/internal/instances/RaceInstance.scala
- modules/kernel/src/main/scala/tofu/Fire.scala
Hi, I'm adding transformers support for `Fire` and `Race` (previos PR https://github.com/tofu-tf/tofu/pull/1245 and https://github.com/tofu-tf/tofu/pull/1252 ). Also fix ide support for correct implicits for `Fire`, `Race`, `Start` (`Fibers`)
> Add transformers support for `Fire` and `Race`

- project/Dependencies.scala
This PR bumps cats-tagless dep up.
It got never merged in terms of https://github.com/tofu-tf/tofu/pull/1264, https://github.com/tofu-tf/tofu/pull/1233, and https://github.com/tofu-tf/tofu/pull/1266
> Update cats-tagless to 0.16.0

- build.sbt
- modules/logging/interop/logstash-logback/src/test/scala/tofu/logging/TofuLoggingProviderSuite.scala
> fix: include logging3 into tofu aggregted modules

- modules/logging/structured/src/main/scala-3/tofu/logging/LoggingRepresentableKInstances.scala
In tofu-logging for Scala 3 a `RepresentableK` instance for `Logging` is not derived but is defined manually. 
That instance does not override `writeMarker` method, but the default `writeMarker` implementation ignores markers.
It can result in marker-erasing implementation for `Logs` if they were constructed using `Mid.attach`
> fix: non-dummy writeMarker in Logging RepresentableK instance in Scala 3

- modules/core/ce2/src/main/scala/tofu/interop/CE2Agents.scala
- modules/core/ce2/src/main/scala/tofu/interop/CE2Kernel.scala
- modules/core/ce2/src/test/scala/tofu/concurrent/PermitSuite.scala
- modules/core/ce3/src/main/scala/tofu/interop/CE3Agents.scala
- modules/core/ce3/src/main/scala/tofu/interop/CE3Kernel.scala
- modules/core/ce3/src/test/scala/tofu/concurrent/PermitSuite.scala
- modules/kernel/src/main/scala-2/tofu/internal/carriers/concurrentMacro.scala
- modules/kernel/src/main/scala-2/tofu/internal/instances/MakePermitInstance.scala
- modules/kernel/src/main/scala-3/tofu/internal/carriers/concurrentMacro.scala
- modules/kernel/src/main/scala-3/tofu/internal/instances/MakePermitInstance.scala
- modules/kernel/src/main/scala/tofu/concurrent/Permit.scala
- modules/kernel/src/main/scala/tofu/internal/carriers/concurrent.scala
Hi, I noticed a disadvantage in tofu that there is no semaphore primitive, but there are concurrent primitives for atomic variables. To avoid creating semaphore based on `Agen`/`QVar`/`Atom`, I suggest to add a new primitive `Permit`, which will use native implementation of the semaphore, depending on the effects.
> Add Permit type like Semaphore

- docs/tofu.logging.recipes.auto.md
- docs/tofu.logging.recipes.context.md
- docs/tofu.logging.recipes.md
- docs/tofu.logging.recipes.simple.md
It seems that at some point in the past, the `examples` branch was deleted, and therefore some links from the documentation became irrelevant. I have updated the links for three examples in logging (simple, service, auto), but there is one broken link left (logback groovy format):
https://github.com/tofu-tf/tofu/blob/e563e36a5c22c4fd36f2d424d152ba6a13d8555d/docs/tofu.logging.recipes.md?plain=1#L15-L17
If you know the new location of this file, please let me know, I will be happy to add the appropriate changes to this pull request.
I have updated the links so that they point to the `master` branch, or more specifically to the `examples/ce2/src/main/scala-2/tofu/example/logging`.
> Update broken links in documentation (logging)

- modules/interop/zio2/logging/src/main/scala/tofu/logging/zlogs/ZLogAnnotation.scala
This PR adds `ZLogAnnotation.makePlain` overload.
Use case:
i.e. given the [example](https://zio.dev/ecosystem/community/tofu-zio2-logging/), the log is printed in the following shape:
```js
{
"level": "INFO",
"logger_name": "my.package.Main",
"message": "Hello, ZIO logging!",
"user": {
"id": 100,
"login": "use*****",
"godMode": false
}
}
```
In some cases we want to lift the underlying values up, outside of the "user" field, to achieve:
```js
{
"level": "INFO",
"logger_name": "my.package.Main",
"message": "Hello, ZIO logging!",
"id": 100,
"login": "use*****",
"godMode": false
}
```
[The reason this PR works](https://github.com/tofu-tf/tofu/blob/master/modules/interop/zio2/logging/src/main/scala/tofu/logging/zlogs/TofuZLogger.scala#L46)
upd: @dos65 asked for some tests; I'll try to find …
> ZLogAnnotation.makePlain annotation

- .github/workflows/ci.yml
Fixes https://github.com/tofu-tf/tofu/actions/runs/16296288588
```
[Invalid workflow file: .github/workflows/ci.yml#L66](https://github.com/tofu-tf/tofu/actions/runs/16296288588/workflow)
The workflow is not valid. .github/workflows/ci.yml (Line: 66, Col: 5): Required property is missing: runs-on
```
> fix: ci docs publish

- ci-release.sbt
See https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html
> Use early-semver for publish
